name: CI

on:
  push:
    branches: [ main, "**" ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Ensure required system tools
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync unzip

      - name: Run setup and tests
        run: |
          bash scripts/setup_env.sh --test

